---
- name: Install Docker
  hosts: all #to add groups use the ones under inventory
  gather_facts: yes

  tasks:
    - name: Check if the VM is running Ubuntu Server
      set_fact:
          is_ubuntu: "{{ ansible_distribution == 'Ubuntu' }}"

    - name: Install Docker prerequisites on Ubuntu
      block:
        - name: Install prerequisite packages
          become: yes
          apt:
            name: "{{ item }}"
            state: present
          loop:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common

        - name: Add Docker's official GPG key
          become: yes
          apt_key:
            url: https://download.docker.com/linux/ubuntu/gpg
            state: present

        - name: Add Docker APT repository
          become: yes
          apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
            state: present

        - name: Update apt package cache and install Docker
          become: yes
          apt:
            name: docker-ce
            state: present
      when: is_ubuntu

    - name: Display message if Docker installation is skipped
      debug:
        msg: "Docker installation skipped as the VM is not running Ubuntu Server"
      when: not is_ubuntu

- name: Deploy portainer-ce latest
  hosts: all
  become: true
  become_user: root

  tasks:
    - name: Create new volume
      community.docker.docker_volume:
        name: portainer-data

    - name: Deploy portainer
      community.docker.docker_container:
        name: portainer
        image: "docker.io/portainer/portainer-ce"
        ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: unless-stopped